[phases.setup]
nixPkgs = [
  'php83Extensions.mysqli',
  'php83Extensions.pdo_mysql',
  'composer'
]

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'chmod +x start-container.sh'
]

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8080} -t /app'
